"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var persona_1 = require("./persona");
var persona1 = new persona_1.Persona('Pablo', 'Pérez', 25, '12345678A', new Date('1993-05-20'), 'rojo', 'H', 'Calle Roja 123', 'pablo@gmail.com', 123456789, 'Notas de Juan');
var persona2 = new persona_1.Persona('María', 'Gómez', 30, '87654321B', new Date('1996-05-21'), 'azul', 'M', 'Calle Azul 456', 'maria@gmail.com', 987654321, 'Notas de María');
var persona3 = new persona_1.Persona('Alejandro', 'Rodriguez', 60, '23456789C', new Date('1993-09-30'), 'verde', 'H', 'Calle Verde 789', 'alejandro@gmail.com', 555555555, 'Notas de Pedro');
console.log("Nombre: ".concat(persona1.getNombre(), ", Apellidos: ").concat(persona1.getApellidos(), ", Edad: ").concat(persona1.getEdad(), ", DNI: ").concat(persona1.getDNI(), ", Cumplea\u00F1os: ").concat(persona1.getCumpleaños(), ", Color Favorito: ").concat(persona1.getColorFav(), ", Sexo: ").concat(persona1.getSexo(), ", Direcci\u00F3n: ").concat(persona1.getDireccion(), ", Mail: ").concat(persona1.getMail(), ", Tel\u00E9fono: ").concat(persona1.getTelefono(), ", Notas: ").concat(persona1.getNotas()));
console.log("Nombre: ".concat(persona2.getNombre(), ", Apellidos: ").concat(persona2.getApellidos(), ", Edad: ").concat(persona2.getEdad(), ", DNI: ").concat(persona2.getDNI(), ", Cumplea\u00F1os: ").concat(persona2.getCumpleaños(), ", Color Favorito: ").concat(persona2.getColorFav(), ", Sexo: ").concat(persona2.getSexo(), ", Direcci\u00F3n: ").concat(persona2.getDireccion(), ", Mail: ").concat(persona2.getMail(), ", Tel\u00E9fono: ").concat(persona2.getTelefono(), ", Notas: ").concat(persona2.getNotas()));
console.log("Nombre: ".concat(persona3.getNombre(), ", Apellidos: ").concat(persona3.getApellidos(), ", Edad: ").concat(persona3.getEdad(), ", DNI: ").concat(persona3.getDNI(), ", Cumplea\u00F1os: ").concat(persona3.getCumpleaños(), ", Color Favorito: ").concat(persona3.getColorFav(), ", Sexo: ").concat(persona3.getSexo(), ", Direcci\u00F3n: ").concat(persona3.getDireccion(), ", Mail: ").concat(persona3.getMail(), ", Tel\u00E9fono: ").concat(persona3.getTelefono(), ", Notas: ").concat(persona3.getNotas()));
